site_name: 'Wakeflow'

repo_name: 'GitHub'
repo_url: 'https://github.com/wakeflow/how-we-do'

# Configuration
theme:
  name: 'material'
  logo: 'images/favicon.png'
  favicon: 'images/favicon.png'
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

nav:
  - Home: index.md
  - Coding:
    - Good Software: good_software.md
    - Contributing: contributing.md
    - Dotfiles: dotfiles.md
    - Javascript: javascript.md
    - Testing: testing.md
    - API Requests: api_requests.md
    - Dates: dates.md
    - Sorting arrays: sorting_arrays.md
    - Styling: css.md
    - Linting: linting.md
    - Secrets: secrets.md
    - Validation: validation.md
    - Deploying: deploying.md
    - CI/CD: cicd.md
    - Firestore Backups: firestore_backups.md
    - Event Tracking: event_tracking.md
  - Professional Development:
    - Train: trainingMaterials.md
    - Holidays: holidays.md
    - Progression: progression.md
    - Developer Bands: developer_bands.md
  


plugins:
  - search
  - minify:
      minify_html: true
